name: tastytakeout_user_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  logger: ^2.0.2+1
  http: ^1.1.2
  provider: ^6.1.1
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.0.6
  shared_preferences: ^2.0.13
  flutter_spinkit: ^5.1.0
  intl: ^0.19.0
  web_socket_channel: ^2.4.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  animated_text_kit: ^4.2.2
  flutter_local_notifications: ^15.1.1
  input_quantity: ^2.2.0
  google_fonts: ^4.0.1
  hexcolor: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/resources/
    - lib/resources/payment_info/
    - lib/resources/user_image1.png
